// scripts/inject-env.js
const fs = require('fs');
const path = require('path');

console.log('Injecting Environment Variables via Node.js...');

const envFileContent = `
// This file is dynamically generated by Cloudflare Pages during the build process
window.ENV = {
  SUPABASE_URL: "${process.env.SUPABASE_URL || ''}",
  SUPABASE_ANON_KEY: "${process.env.SUPABASE_ANON_KEY || ''}"
};
`;

const outputPath = path.join(__dirname, '..', 'js', 'env.js');
fs.writeFileSync(outputPath, envFileContent.trim(), 'utf8');

console.log('js/env.js created successfully!');