// scripts/inject-env.js
const fs = require('fs');
const path = require('path');

console.log('Building supabase-client.js with environment variables...');

const clientContent = `
// js/supabase-client.js
// This file was dynamically generated by Cloudflare Pages during the build process.

const SUPABASE_URL = "${process.env.SUPABASE_URL || ''}";
const SUPABASE_ANON_KEY = "${process.env.SUPABASE_ANON_KEY || ''}";

if (SUPABASE_URL && SUPABASE_URL.startsWith('http')) {
    window.supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
    console.log('Supabase Client Initialized.');
} else {
    console.warn("Supabase Client failed to initialize: Invalid or missing SUPABASE_URL environment variable.");
}
`;

const outputPath = path.join(__dirname, '..', 'js', 'supabase-client.js');
fs.writeFileSync(outputPath, clientContent.trim(), 'utf8');

console.log('js/supabase-client.js built successfully!');